config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#top'
  get  "home/about" => "users#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :books do
  	resource :favorites
  	resource :book_comments
  end
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'users/follows/:id' => 'relationships#follower', as: 'follows'
  get 'users/followers/:id' => 'relationships#followed', as: 'followers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
		user_path(resource.id)
	end

	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	    added_attrs = [:user_name, :email, :password, :password_confirmation, :remember_me]
	    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
	    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def index
		@book_comments = BookComment.all
	end
	def create
		book = Book.find(params[:book_id])
		comment = current_user.book_comments.new(book_comment_params)
		comment.book_id = book.id
		comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
  	@books = Book.all
  	@book = Book.new
    @user = User.find(current_user.id)
  end

  def show
  	@book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
    @user = User.find(current_user.id)
    if @book.save
      flash[:notice] = "You have creatad book successfully."
  	  redirect_to book_path(@book.id)
    else
      @books = Book.all
      flash.now[:alert] = "error"
      render :index
    end
  end

  def edit
    @book = Book.new
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      flash.now[:alert] = "error"
      render action: :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow
		current_user.follow(params[:id])
		redirect_back(fallback_location: root_path)
	end

	def unfollow
		current_user.unfollow(params[:id])
		redirect_back(fallback_location: root_path)
	end

	def follower
		user = User.find(params[:id])
		@users = user.following_user
	end

	def followed
		user = User.find(params[:id])
		@users = user.follower_user
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:top, :about]

  def top
  end

  def about
  end

  def new
    @book = Book.new #
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new #
    @books = @user.books
  end

  def edit
     @user = User.find(params[:id])
     if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    	redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "error"
      render action: :edit
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :profile_image, :introduction)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">

	<% if @book.errors.any? %>
		<div id="error_explanation" class="alert alert-danger">
			<ul>
				<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="row">
		<div class="col-xs-6 col-xs-offset-3">
			<h1>Editing Book</h1>

			<%= form_for(@book) do |f| %>
				<h4>Title</h4>
				<%= f.text_field :title %>
				<h4>Opinion</h4>
				<%= f.text_area :body %>
				<%= f.submit "Update Book" %>
			<% end %>

			<%= link_to "Show", book_path(@book.id) %>
			|
			<%= link_to "Back", books_path %>

		</div>
	</div>
</div>

app/views/books/index.html.erb
<body>

	<div class=container>


		<% if @book.errors.any? %>
			 <div id="error_explanation" class="alert alert-danger">
				<ul>
				    <% @book.errors.full_messages.each do |message| %>
				    <li><%= message %></li>
				    <% end %>
				</ul>
			</div>
		<% end %>


		<div class=row>
			<div class="col-xs-3">
				<h2>User info</h2>
				<table class="table table-striped">
					<tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpeg" %></tr>
					<tr>
						<th>name</th>
						<th>
							<%= @user.name %>
						</th>
					</tr>
					<tr>
						<th>introduction</th>
						<th>
							<%= @user.introduction %>
						</th>
					</tr>
					<tr>
						<th>follows</th>
						<th><%= @user.follower.count %></th>
					</tr>
					<tr>
						<th>followers</th>
						<th><%= @user.followed.count %></th>
					</tr>
				</table>
				<div class=row>
					<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
				</div>

				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<label for="title">Title</label><br>
					<%= f.text_field :title %><br>
					<label for="opinion">Opinion</label><br>
					<%= f.text_area :body %><br>
					<%= f.submit "Create Book" %>
				<% end %>
			</div>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
							<tr>
								<td>
									<%= link_to user_path(book.user_id) do %>
										<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
									<% end %>
								</td>
								<td>
									<%= link_to book_path(book.id) do %>
										<%= book.title %>
									<% end %>
								</td>
								<td><%= book.body %></td>
								<% if book.favorited_by?(current_user) %>
									<td>
										<%= link_to book_favorites_path(book), method: :delete do %>
											<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
											<%= book.favorites.count %>
										<% end %>
									</td>
								<% else %>
									<td>
										<%= link_to book_favorites_path(book), method: :post do %>
											<i class="fa fa-heart-o" aria-hidden="true"></i>
											<%= book.favorites.count %>
										<% end %>
									</td>
								<% end %>
								<td>コメント数：<%= book.book_comments.count %> </td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

</body>

app/views/books/new.html.erb
<%= form_for(@book) do |f| %>
	<label for="title">Title</label><br>
	<%= f.text_field :title, id:"title" %><br>
	<label for="opinion">Opinion</label><br>
	<%= f.text_area :body, id:"opinion" %><br>
	<%= f.submit "Create Book" %>
<% end %>

<footer>
    <div class="container">
    	<div class="row">
    		<div class="col-xs-3 col-xs-offset-9">
    			<p>CopyRight Infratop.inc</p>
    		</div>
        </div>
    </div>
</footer>

app/views/books/show.html.erb
<body>

	<div class=container>
		<div class=row>
			<div class="col-xs-3">
				<h2>User info</h2>
				<table class="table table-striped">
					<tr><%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpeg" %></tr>
					<tr>
						<th>name</th>
						<th>
							<%= @book.user.name %>
						</th>
					</tr>
					<tr>
						<th>introduction</th>
						<th>
							<%= @book.user.introduction %>
						</th>
					</tr>
				</table>
				<div class=row>
					<% if @book.user==current_user %>
						<%= link_to "", edit_user_path, class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
					<% else %>
						<%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
					<% end %>

				</div>
				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<label for="title">Title</label><br>
					<%= f.text_field :title %><br>
					<label for="opinion">Opinion</label><br>
					<%= f.text_area :body %><br>
					<%= f.submit "Create Book" %>
				<% end %>
			</div>
			<div class="col-xs-9">
				<h2>Book detail</h2>
				<table class="table table-hover table-inverse">
					<tbody>
						<tr>
							<td>
								<%= link_to user_path(@book.user_id) do %>
									<%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %><br>
										<%= @book.user.name %>
								<% end %>
							</td>
							<td>
								<%= link_to book_path(@book.id) do %>
									<%= @book.title %>
								<% end %>
							</td>
							<td><%= @book.body %></td>
							<% if @book.user == current_user %>
								<td><%= link_to "Edit", edit_book_path, class: "btn-sm btn-success" %></td>
								<td><%= link_to "Destroy", book_path(@book.id), method: :delete,class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %></td>
							<% end %>
							<% if @book.favorited_by?(current_user) %>
								<td>
									<%= link_to book_favorites_path(@book), method: :delete do %>
										<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
										<%= @book.favorites.count %>
									<% end %>
								</td>
							<% else %>
								<td>
									<%= link_to book_favorites_path(@book), method: :post do %>
										<i class="fa fa-heart-o" aria-hidden="true"></i>
										<%= @book.favorites.count %>
									<% end %>
								</td>
							<% end %>
							<td>コメント数：<%= @book.book_comments.count %> </td>
							</tr>
					</tbody>
				</table>
				<%= form_for [@book, @book_comment] do |f| %>
					<%= f.text_area :comment %>
					<%= f.submit "送信", class:"btn btn-lg btn-base-1 pull-right" %>
				<% end %>
				<h2>Comments</h2>
				<tbody>
					<% @book_comments.each do |book_comments| %>
						<tr> <%= book_comments.comment %> </tr>
					<% end %>
				</tbody>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse" style="color: white">

      <div id="container">
        <div id="theTarget">
          <div class="image1"></div>
          <div class="image2"></div>
          <div class="image3"></div>
          <div class="image4"></div>
          <div class="image5"></div>
        </div>
      </div>


      <div class="container">
        <nav class="nav navbar-nav navbar-left" style="font-size: 20px">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav nav-tabs navbar navbar-right">
            <% if user_signed_in? %>
              <li >
                <%= link_to user_path(current_user.id), :style=>"color:white;" do %>
                  <i class="glyphicon glyphicon-home home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path, :style=>"color:white;" do %>
                  <i class="glyphicon glyphicon-user users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path, :style=>"color:white;" do %>
                 <i class="glyphicon glyphicon-book books"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, :style=>"color:white;" do %>
                  <i class="glyphicon glyphicon-log-out logout"></i> logout
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path, :style=>"color:white;" do %>
                    <i class="glyphicon glyphicon-home home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path, :style=>"color:white;" do %>
                   <i class="glyphicon glyphicon-link about"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path, :style=>"color:white;" do %>
                   <i class="glyphicon glyphicon-edit sign_up"></i> sign up
                  <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, :style=>"color:white;" do %>
                  <i class="glyphicon glyphicon-log-in sign_in"></i>login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header><!-- /header -->

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/relationships/followed.html.erb
<body>
	<div class=container>
		<div class=row>
			<div class="col-xs-9">
				<h2>Follower Users</h2>
				<% if @users.count > 0 %>
					<table class="table table-hover table-inverse">
						<thead>
							<tr>
								<th>image</th>
								<th>name</th>
							</tr>
						</thead>
						<tbody>
							<% @users.each do |user| %>
								<tr>
									<td>
										<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
									</td>
									<td>
										<%= user.name %>
									</td>
									<td>
										フォロー数：<%= user.follower.count %>
									</td>
									<td>
										フォロワー数：<%= user.followed.count %>
									</td>
									<td>
										<% if current_user.following?(user) %>
											<%= link_to "フォロー外す", unfollow_path(user.id), method: :post %>
									    <% else %>
									    	<%= link_to "フォローする", follow_path(user.id), method: :post %>
										<% end %>
									</td>
									<td>
										<%= link_to "Show", user_path(user.id) %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<p>ユーザーはいません</p>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/relationships/follower.html.erb
<body>
	<div class=container>
		<div class=row>
			<div class="col-xs-9">
				<h2>Follow Users</h2>
				<% if @user.count > 0 %>
					<table class="table table-hover table-inverse">
						<thead>
							<tr>
								<th>image</th>
								<th>name</th>
							</tr>
						</thead>
						<tbody>
							<% @users.each do |user| %>
								<tr>
									<td>
										<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
									</td>
									<td>
										<%= user.name %>
									</td>
									<td>
										フォロー数：<%= user.follower.count %>
									</td>
									<td>
										フォロワー数：<%= user.followed.count %>
									</td>
									<td>
										<% if current_user.following?(user) %>
											<%= link_to "フォロー外す", unfollow_path(user.id), method: :post %>
									    <% else %>
									    	<%= link_to "フォローする", follow_path(user.id), method: :post %>
										<% end %>
									</td>
									<td>
										<%= link_to "Show", user_path(user.id) %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<p>ユーザーはいません</p>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/users/about.html.erb
<div class="container">
	<h1>
		welcome to
		<span class="glyphicon glyphicon-book">
		<strong>Bookers</strong>!!
		</span>
	</h1>
</div>

<footer>
    <div class="container">
        <div class="row">
        	<div class="col-xs-3 col-xs-offset-9">
            	<p>CopyRight Infratop.inc</p>
        	</div>
    	</div>
   	</div>
</footer>

app/views/users/followers.html.erb
<div class=container>
	<div class=row>
		<div class="col-xs-6 col-xs-offset-3">
			<h2>follows</h2>
			<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
						</tr>
					</thead>
					<tbody>
						<% @user.follower_user do |user| %>
							<tr>
								<td>
									<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
								</td>
								<td>
									<%= user.name %>
								</td>
								<td>
									フォロー数：<%= user.follower.count %>
								</td>
								<td>
									フォロワー数：<%= user.followed.count %>
								</td>
								<td>
									<% if current_user.following?(user) %>
										<%= link_to "フォロー外す", unfollow_path(user.id), method: :post %>
								    <% else %>
								    	<%= link_to "フォローする", follow_path(user.id), method: :post %>
									<% end %>
								</td>
								<td>
									<%= link_to "Show", user_path(user.id) %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/users/follows.html.erb
<div class=container>
	<div class=row>
		<div class="col-xs-6 col-xs-offset-3">
			<h2>follows</h2>
			<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
						</tr>
					</thead>
					<tbody>
						<% @user.following_user do |user| %>
							<tr>
								<td>
									<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
								</td>
								<td>
									<%= user.name %>
								</td>
								<td>
									フォロー数：<%= user.follower.count %>
								</td>
								<td>
									フォロワー数：<%= user.followed.count %>
								</td>
								<td>
									<% if current_user.following?(user) %>
										<%= link_to "フォロー外す", unfollow_path(user.id), method: :post %>
								    <% else %>
								    	<%= link_to "フォローする", follow_path(user.id), method: :post %>
									<% end %>
								</td>
								<td>
									<%= link_to "Show", user_path(user.id) %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<body>

	<div class=container>
		<div class=row>
			<div class="col-xs-3">
				<h2>User info</h2>
				<table class="table table-striped">
					<tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpeg" %></tr>
					<tr>
						<th>name</th>
						<th>
							<%= @user.name %>
						</th>
					</tr>
					<tr>
						<th>introduction</th>
						<th>
							<%= @user.introduction %>
						</th>
					</tr>
					<tr>
						<th>follows</th>
						<th><%= @user.follower.count %></th>
					</tr>
					<tr>
						<th>followers</th>
						<th><%= @user.followed.count %></th>
					</tr>
				</table>
				<div class=row>
					<%= link_to "", edit_user_path(@user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
				</div>

				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<label for="title">Title</label><br>
					<%= f.text_field :title, id:"title" %><br>
					<label for="opinion">Opinion</label><br>
					<%= f.text_area :body, id:"opinion" %><br>
					<%= f.submit "Create Book" %>
				<% end %>
			</div>
			<div class="col-xs-9">
				<h2>Users</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th>image</th>
							<th>name</th>
						</tr>
					</thead>
					<tbody>
						<% @users.each do |user| %>
							<tr>
								<td>
									<%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
								</td>
								<td>
									<%= user.name %>
								</td>
								<td>
									フォロー数：<%= user.follower.count %>
								</td>
								<td>
									フォロワー数：<%= user.followed.count %>
								</td>
								<td>
									<% if current_user.following?(user) %>
										<%= link_to "フォロー外す", unfollow_path(user.id), method: :post %>
								    <% else %>
								    	<%= link_to "フォローする", follow_path(user.id), method: :post %>
									<% end %>
								</td>
								<td>
									<%= link_to "Show", user_path(user.id) %>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

</body>

app/views/users/show.html.erb
<body>

	<div class=container>
		<div class=row>
			<div class="col-xs-3">
				<h2>User info</h2>
				<table class="table table-striped">
					<tr><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpeg" %></tr>
					<tr>
						<th>name</th>
						<th>
							<%= @user.name %>
						</th>
					</tr>
					<tr>
						<th>introduction</th>
						<th>
							<%= @user.introduction %>
						</th>
					</tr>
					<tr>
						<th>follows</th>
						<th>
							<%= link_to @user.follower.count, follows_path(@user.id) %>
						</th>
					</tr>
					<tr>
						<th>followers</th>
						<th>
							<%= link_to @user.followed.count, followers_path(@user.id) %>
						</th>
					</tr>
				</table>
				<div class=row>
					<% if @user!=current_user %>
						<% if current_user.following?(@user) %>
							<%= link_to "フォロー外す", unfollow_path(@user.id), method: :post, class: "col-xs-12 btn btn-default", style: "background-color: green" %>
						<% else %>
							<%= link_to "フォローする", follow_path(@user.id), method: :post, class: "col-xs-12 btn btn-default", style: "background-color: green" %>
						<% end %>
					<% end %>
				</div>
				<div class=row>
					<% if @user==current_user %>
						<%= link_to "", edit_user_path, class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
					<% else %>
						<%= link_to "", user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
					<% end %>
				</div>

				<h2>New book</h2>
				<%= form_for(@book) do |f| %>
					<label for="title">Title</label><br>
					<%= f.text_field :title, id:"title" %><br>
					<label for="opinion">Opinion</label><br>
					<%= f.text_area :body, id:"opinion" %><br>
					<%= f.submit "Create Book" %>
				<% end %>
			</div>
			<div class="col-xs-9">
				<h2>Books</h2>
				<table class="table table-hover table-inverse">
					<thead>
						<tr>
							<th></th>
							<th>Title</th>
							<th>Opinion</th>
						</tr>
					</thead>
					<tbody>
						<% @books.each do |book| %>
							<tr>
								<td>
									<%= link_to user_path(params[:id]) do %>
										<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpeg" %>
									<% end %>
								</td>
								<td>
									<%= link_to book_path(book.id) do %>
										<%= book.title %>
									<% end %>
								</td>
								<td><%= book.body %></td>
								<td>コメント数：<%= book.book_comments.count %> </td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

</body>